# Dockerfile.dev
FROM elixir:1.17

# Install dev dependencies
RUN apt-get update && \
    apt-get install -y build-essential git curl inotify-tools nodejs npm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Phoenix
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install hex phx_new --force

# Set working directory
WORKDIR /app

# Set environment variables
ENV MIX_ENV=dev \
    LANG=C.UTF-8

# Expose Phoenix port and LiveReload port
EXPOSE 4000 4001

# Default command (will be overridden in docker-compose)
CMD ["/bin/bash"]